version: '3'

services:
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
    networks:
      - local

  server:
    restart: always
    build: ./server
    expose:
      - "5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - FLASK_ENV=production
    networks:
      - local

  client:
    restart: always
    build: ./client
    ports:
      - "8080:8080"
    depends_on:
      - server
    networks:
      - local

  nginx:
    image: nginx:1.13.7
    depends_on:
      - server
      - client
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - local
    ports:
      - "80:80"

networks:
  local:
    driver: bridge

volumes:
  db-data: