version: '2'

services:
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "postgres"

  server:
    restart: always
    build: ./server
    expose:
      - "5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres

  client:
    restart: always
    build: ./client
    ports:
      - "8080:8080"
    depends_on:
      - server


volumes:
  db-data: